name: Go
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - "1.19"
        - "1.20"
    name: Go Build with ${{ matrix.go }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: Check out code
      uses: actions/checkout@v1
    - name: Build
      run: go build -v ./...
    - name: Test
      run: |
        ./.test.sh
    - name: Upload coverage to codecov.io
      env:
        codecov_token: ${{secrets.CODECOV_TOKEN}}
      run: |
        bash <(curl -s https://codecov.io/bash)
